version: '3'
services:

  web:
    image: nginx:alpine
    restart: always
    ports:
      - '80:80'
    environment:
      TZ: Asia/Tokyo
    volumes:
      - php-fpm:/var/run/php-fpm:rw
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./laravel:/var/www/html:ro
    depends_on:
      - app

  app:
    build:
      context: ./docker/php-fpm
    environment:
      TZ: Asia/Tokyo
    volumes:
      - php-fpm:/var/run/php-fpm:rw
      - ./docker/php-fpm/php.ini:/usr/local/php/php.ini:ro
      - ./docker/php-fpm/php-fpm.d:/usr/local/etc/php-fpm.d:ro
      - ./laravel:/var/www/html:rw
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      TZ: Asia/Tokyo
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql:rw
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d:ro
      - ./docker/mysql/conf.d:/etc/mysql/conf.d:ro

volumes:
  db:
  php-fpm:
